# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build pipeline

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]

jobs:
  build_library:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global deps
        run: |
          npm install -g @angular/cli
      - name: Install project dependencies
        run: npm install
      - name: Lint library project
        run: ng lint --project ngx-formulus
      - name: Build library
        run: npm run build_lib
  build_showcase:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global deps
        run: |
          npm install -g @angular/cli
      - name: Install project dependencies
        run: npm install
      - name: Lint library example project
        run: ng lint --project ngx-formulus-example
      - name: Build example
        run: cd projects/ngx-formulus-example && ng build --project ngx-formulus-example
